name: GHAction – Zadanie 2 CI/CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, scan and push Docker image to DockerHub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Docker metadata definitions
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/zadanie2
        flavor: latest=true
        tags: |
          type=sha,priority=100,prefix=sha-,format=short
          type=semver,priority=200,pattern={{version}}
          type=ref,event=branch

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache,mode=max
        tags: ${{ steps.meta.outputs.tags }}

    - name: Run Trivy CVE scan (fail on HIGH or CRITICAL)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/zadanie2:sha-${{ github.sha }}
        format: 'table'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        exit-code: '1'